

title: CSS-Advanced
email: kristina@example.com
description: some description whatfack ever
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook: k.chausheva
github_username:  KristinaChausheva
demovar: demovar

markdown: kramdown
plugins:
  - jekyll-feed


#exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
